In [1]:
data = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81]
print(data)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81]


In [2]:
import numpy as np
def splitSequence(seq, n_steps):
    
    #Declare X and y as empty list
    X = []
    y = []
    
    for i in range(len(seq)):
        #get the last index
        lastIndex = i + n_steps
        
        #if lastIndex is greater than length of sequence then break
        if lastIndex > len(seq) - 1:
            break
            
        #Create input and output sequence
        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]
        
        #append seq_X, seq_y in X and y list
        X.append(seq_X)
        y.append(seq_y)
        pass
    #Convert X and y into numpy array
    X = np.array(X)
    y = np.array(y)
    
    return X,y 
    
    pass

In [3]:
n_steps = 5
X, y = splitSequence(data, n_steps = 5)

In [4]:
print(X)


[[ 1  3  5  7  9]
 [ 3  5  7  9 11]
 [ 5  7  9 11 13]
 [ 7  9 11 13 15]
 [ 9 11 13 15 17]
 [11 13 15 17 19]
 [13 15 17 19 21]
 [15 17 19 21 23]
 [17 19 21 23 25]
 [19 21 23 25 27]
 [21 23 25 27 29]
 [23 25 27 29 31]
 [25 27 29 31 33]
 [27 29 31 33 35]
 [29 31 33 35 37]
 [31 33 35 37 39]
 [33 35 37 39 41]
 [35 37 39 41 43]
 [37 39 41 43 45]
 [39 41 43 45 47]
 [41 43 45 47 49]
 [43 45 47 49 51]
 [45 47 49 51 53]
 [47 49 51 53 55]
 [49 51 53 55 57]
 [51 53 55 57 59]
 [53 55 57 59 61]
 [55 57 59 61 63]
 [57 59 61 63 65]
 [59 61 63 65 67]
 [61 63 65 67 69]
 [63 65 67 69 71]
 [65 67 69 71 73]
 [67 69 71 73 75]
 [69 71 73 75 77]
 [71 73 75 77 79]]


In [5]:
print(y)

[11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57
 59 61 63 65 67 69 71 73 75 77 79 81]


In [6]:
for i in range(len(X)):
    print(X[i], y[i])

[1 3 5 7 9] 11
[ 3  5  7  9 11] 13
[ 5  7  9 11 13] 15
[ 7  9 11 13 15] 17
[ 9 11 13 15 17] 19
[11 13 15 17 19] 21
[13 15 17 19 21] 23
[15 17 19 21 23] 25
[17 19 21 23 25] 27
[19 21 23 25 27] 29
[21 23 25 27 29] 31
[23 25 27 29 31] 33
[25 27 29 31 33] 35
[27 29 31 33 35] 37
[29 31 33 35 37] 39
[31 33 35 37 39] 41
[33 35 37 39 41] 43
[35 37 39 41 43] 45
[37 39 41 43 45] 47
[39 41 43 45 47] 49
[41 43 45 47 49] 51
[43 45 47 49 51] 53
[45 47 49 51 53] 55
[47 49 51 53 55] 57
[49 51 53 55 57] 59
[51 53 55 57 59] 61
[53 55 57 59 61] 63
[55 57 59 61 63] 65
[57 59 61 63 65] 67
[59 61 63 65 67] 69
[61 63 65 67 69] 71
[63 65 67 69 71] 73
[65 67 69 71 73] 75
[67 69 71 73 75] 77
[69 71 73 75 77] 79
[71 73 75 77 79] 81


In [7]:
# reshape `
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
print(X[:2])

[[[ 1]
  [ 3]
  [ 5]
  [ 7]
  [ 9]]

 [[ 3]
  [ 5]
  [ 7]
  [ 9]
  [11]]]


In [8]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [9]:
model = tf.keras.Sequential()
model.add(layers.LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(layers.Dense(1))

2022-07-06 08:04:47.407538: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [10]:
model.layers

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 50)                10400     
_________________________________________________________________
dense (Dense)                (None, 1)                 51        
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.01),
loss=tf.keras.losses.MeanSquaredError(), metrics=['accuracy'])

In [13]:
model.fit(X, y, epochs=200, verbose=1)

Epoch 1/200


2022-07-06 08:04:47.945964: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


2/2 [==============================] - 2s 9ms/step - loss: 2771.8413 - accuracy: 0.0000e+00
Epoch 2/200
2/2 [==============================] - 0s 6ms/step - loss: 1241.5507 - accuracy: 0.0000e+00
Epoch 3/200
2/2 [==============================] - 0s 6ms/step - loss: 127.8370 - accuracy: 0.0000e+00
Epoch 4/200
2/2 [==============================] - 0s 5ms/step - loss: 30.2702 - accuracy: 0.0000e+00
Epoch 5/200
2/2 [==============================] - 0s 6ms/step - loss: 14.2976 - accuracy: 0.0000e+00
Epoch 6/200
2/2 [==============================] - 0s 6ms/step - loss: 24.2909 - accuracy: 0.0000e+00
Epoch 7/200
2/2 [==============================] - 0s 5ms/step - loss: 15.2934 - accuracy: 0.0000e+00
Epoch 8/200
2/2 [==============================] - 0s 6ms/step - loss: 11.6571 - accuracy: 0.0000e+00
Epoch 9/200
2/2 [==============================] - 0s 5ms/step - loss: 14.1346 - accuracy: 0.0000e+00
Epoch 10/200
2/2 [==============================] - 0s 6ms/step - loss: 12.6590 - accurac

In [14]:
test_data = np.array([5, 11, 13, 17, 19])
test_data = test_data.reshape((1, n_steps, n_features))
test_data

array([[[ 5],
        [11],
        [13],
        [17],
        [19]]])

In [15]:
predictNextNumber = model.predict(test_data, verbose=1)
print(predictNextNumber)

1/1 [==============================] - 0s 265ms/step
[[18.679724]]
